### ISSUE TITLE
Checklist Administration Task lookup only shows the top video experience type

### ISSUE THREAD

**Issue by rellorin-accessit** [microsoft/AL#7066]
Please include the following with each issue:

**1. Describe the bug**
When creating a new Checklist via Checklist administration, and the selected "Guided Experience Type" is "Video", clicking the Lookup will only display 1 row, which would be the top row on the "Guided Experience Item" table when filtered "Guided Experience Type" = Video.

**2. To Reproduce**

1. First, a "Guided Experience item" where "Guided Experience Type" = video must be inserted into the "Guided Experience Item" table. This is done using the InsertVideo façade functions in the Guided Experience codeunit, as explained [here on microsoft documentation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/onboarding-checklist)
2.  After a "Video" type record exists on the Guided Experience Item table, in BC navigate to Checklist Administration
3. Select "new" at the top
4. for "Guided Experience Type" select "Video
5. in task, select the assist edit lookup

It will only show 1 row

in codeunit 1991 "Guided Experience Impl."

``` AL

local procedure InsertGuidedExperienceItemsInTempVar(var GuidedExperienceItem: Record "Guided Experience Item"; var GuidedExperienceItemTemp: Record "Guided Experience Item" temporary)
    var
        PrevGuidedExperienceItem: Record "Guided Experience Item";
    begin
        repeat
            if (GuidedExperienceItem."Object Type to Run" <> PrevGuidedExperienceItem."Object Type to Run")
                or (GuidedExperienceItem."Object ID to Run" <> PrevGuidedExperienceItem."Object ID to Run")
                or (GuidedExperienceItem.Link <> PrevGuidedExperienceItem.Link)
                or (GuidedExperienceItem."Guided Experience Type" <> PrevGuidedExperienceItem."Guided Experience Type")
                or (GuidedExperienceItem."Spotlight Tour Type" <> PrevGuidedExperienceItem."Spotlight Tour Type")
            then
                InsertGuidedExperienceItemIfValid(GuidedExperienceItemTemp, GuidedExperienceItem);

            PrevGuidedExperienceItem := GuidedExperienceItem;
        until GuidedExperienceItem.Next() = 0;
    end;
```

Because of this function, it will only select the top video record on the Guided Experience item table. The InsertVideo function does not have parameters for Object Type to run, Object ID to run, Link, and Spotlight Tour Type. Because the "Guided Experience Type" will always be "Video" then it will only select the 1st row.

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
A list of ALL the "Guided Experience Item" types of "Video" needs to appear, not just the top 1.

**4. Actual behavior**
Only the top record on the "Guided Experience Item" table where "Guided Experience Type" of "Video" is shown.

**5. Versions:**

- AL Language: 9.0.615906
- Visual Studio Code: 1.66.2
- Business Central: 20.1
- List of Visual Studio Code extensions that you have installed:
- AL Language, AL Toolbox, Git History, GitLens - Git supercharted, Powerhshell, waldo's CRS AL Language Extension

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by dnpb** [comment]
You probably have to report this via partner support, as it's not on-topic here as it's not about the AL language or compiler itself, but rather Base or System App functionality.

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

**Comment by rellorin-accessit** [comment]
Will do - thanks!
