### ISSUE TITLE
API -  POST to Service Comment Line Table

### ISSUE THREAD

**Issue by scruffy-sjb** [microsoft/AL#7500]
<!--

**1. Describe the bug**
Developing a web application to log service calls as service orders into BC.  Cannot POST comments into the Service Comment Line Table using PostMan.

tablename always defaults to "Service Contract Header"

{
    "error": {
        "code": "Internal_InvalidTableRelation",
        "message": "The field No. of table Service Comment Line contains a value (SO000017) that cannot be found in the related table (Service Contract Header).  CorrelationId:  90dd66c5-e7f6-4633-967a-854d498caf0f."
    }
}

**2. To Reproduce**
In PostMan the body I used is
{
            "type": "Fault",
            "number": "SO000017",
            "tablelineno": 10000,
            "lineno": 20000,
            "comment": "This is all messed up",
            "tablesubtype": "1",
            "tablename": "Service Header"
}

I have tried multiple things, such as using an integer for the Enum fields. 

``` AL
page 50114 "API Service Comment Lines"
{
    PageType = API;

    APIVersion = 'v2.0', 'v1.0';
    APIPublisher = 'BC_IMECTech';
    APIGroup = 'imec';

    EntityCaption = 'Service Comment Line';
    EntitySetCaption = 'Service Comment Lines';
    EntityName = 'serviceCommentLine';
    EntitySetName = 'serviceCommentLines';

    ODataKeyFields = SystemId;
    SourceTable = "Service Comment Line";

    Extensible = false;
    DelayedInsert = true;

    layout
    {
        area(content)
        {
            repeater(Group)
            {
                field(id; Rec.SystemId)
                {
                    Caption = 'Id';
                    Editable = false;
                }
                field(lastModifiedDateTime; Rec.SystemModifiedAt) { }
                field(type; rec.Type)
                {
                    Caption = 'Type';
                }
                field(number; rec."No.")
                {
                    Caption = 'No.';
                }
                field(tablelineno; rec."Table Line No.")
                {
                    Caption = 'Table Line No.';
                }
                field(lineno; rec."Line No.")
                {
                    Caption = 'Line No.';
                }
                field(comment; rec.Comment)
                {
                    Caption = 'Comment';
                }
                field(date; rec.Date)
                {
                    Caption = 'Date';
                }
                field(tablesubtype; rec."Table Subtype")
                {
                    Caption = 'Table Subtype';
                }
                field(tablename; rec."Table Name")
                {
                    Caption = 'Table Name';

                    trigger OnValidate()
                    begin
                        RegisterFieldSet(Rec.FieldNo("Table Name"));
                    end;
                }
            }
        }
    }

    var
        TempFieldSet: Record Field temporary;

    local procedure RegisterFieldSet(FieldNumber: Integer)
    begin
        if TempFieldSet.Get(Database::"Service Comment Line", FieldNumber) then
            exit;

        TempFieldSet.Init();
        TempFieldSet.TableNo := Database::"Service Comment Line";
        TempFieldSet."No." := FieldNumber;
        TempFieldSet.Insert();
    end;
}
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
I expected the API to POST a record to the Service Comment Line table.

**4. Actual behavior**
Error ocurs.

{
    "error": {
        "code": "Internal_InvalidTableRelation",
        "message": "The field No. of table Service Comment Line contains a value (SO000017) that cannot be found in the related table (Service Contract Header).  CorrelationId:  90dd66c5-e7f6-4633-967a-854d498caf0f."
    }
}

**5. Versions:**

- AL Language:
![image](https://github.com/microsoft/AL/assets/19880154/c1af7740-e680-42bd-8949-0f531fc71a52)

- Visual Studio Code: 
- Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

- Business Central: 22.4.59114.59220

- List of Visual Studio Code extensions that you have installed:
![image](https://github.com/microsoft/AL/assets/19880154/578088c5-1d21-44c3-b004-f1d4599246ac)

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by EmilDamsbo** [comment]
Missing any actionable info. Please add information about your issue, though I suspect from the title that it is outside the scope of this issue tracker.

**Comment by scruffy-sjb** [comment]
page 50114 "API Service Comment Lines"

{

    PageType = API;

 

    APIVersion = 'v2.0', 'v1.0';

    APIPublisher = 'BC_IMECTech';

    APIGroup = 'imec';

 

    EntityCaption = 'Service Comment Line';

    EntitySetCaption = 'Service Comment Lines';

    EntityName = 'serviceCommentLine';

    EntitySetName = 'serviceCommentLines';

 

    ODataKeyFields = SystemId;

    SourceTable = "Service Comment Line";

 

    Extensible = false;

    DelayedInsert = true;

 

    layout

    {

        area(content)

        {

            repeater(Group)

            {

                field(id; Rec.SystemId)

                {

                    Caption = 'Id';

                    Editable = false;

                }

                field(lastModifiedDateTime; Rec.SystemModifiedAt) { }

                field(type; rec.Type)

                {

                    Caption = 'Type';

                }

                field(number; rec."No.")

                {

                    Caption = 'No.';

                }

                field(tablelineno; rec."Table Line No.")

                {

                    Caption = 'Table Line No.';

                }

                field(lineno; rec."Line No.")

                {

                    Caption = 'Line No.';

                }

                field(comment; rec.Comment)

                {

                    Caption = 'Comment';

                }

                field(date; rec.Date)

                {

                    Caption = 'Date';

                }

                field(tablesubtype; rec."Table Subtype")

                {

                    Caption = 'Table Subtype';

                }

                field(tablename; rec."Table Name")

                {

                    Caption = 'Table Name';

 

                    trigger OnValidate()

                    begin

                        RegisterFieldSet(Rec.FieldNo("Table Name"));

                    end;

                }

            }

        }

    }

 

    var

        TempFieldSet: Record Field temporary;

 

    local procedure RegisterFieldSet(FieldNumber: Integer)

    begin

        if TempFieldSet.Get(Database::"Service Comment Line", FieldNumber) then

            exit;

 

        TempFieldSet.Init();

        TempFieldSet.TableNo := Database::"Service Comment Line";

        TempFieldSet."No." := FieldNumber;

        TempFieldSet.Insert();

    end;

}

**Comment by scruffy-sjb** [comment]
API call to POST to this table always fails. GET works fine. 

POST  keeps defaulting to the Service Contract Header table (an enum of  0) rather than the Service Header Table which is an enum of 1.

**Comment by christianbraeunlich** [comment]
Hi @scruffy-sjb,

would like to politely mention, as it says in the README.md of this repository: "The main purpose of this repository is to track issues regarding the latest version of the AL compiler and developer tools available in the [...]"

The problem you're describing, is not a particular AL compiler issue. So this issue can be closed.

---

I've copyied your provided custom api page into my local project and created the following HTTP request:

```HTTP
POST /BC/api/BC_IMECTech/imec/v1.0/companies(9c09a5ea-0d56-ee11-8df3-6045bdc8df66)/serviceCommentLines?tenant=default HTTP/1.1
Host: bcserver:7048
Content-Length: 161

{
    "tablename": "Service Header",
    "tablesubtype": "1",
    "number": "TEST001",
    "type": "General",
    "tablelineno": 10000,
    "lineno": 10
}
```

Results in:

```JSON
{
    "error": {
        "code": "Internal_InvalidTableRelation",
        "message": "The field No. of table Service Comment Line contains a value (TEST001) that cannot be found in the related table (Service Header).  CorrelationId:  cb77df3c-d204-420e-b338-0cb37856b645."
    }
}
```

Now I create a service request that matches the intent of my HTTP request, send the HTTP request again and get the following result:

```JSON
{
    "@odata.context": "http://bcserver:7048/BC/api/BC_IMECTech/imec/v1.0/$metadata#companies(9c09a5ea-0d56-ee11-8df3-6045bdc8df66)/serviceCommentLines/$entity",
    "@odata.etag": "W/\"JzIwOzExNzI1NjMzOTI3NzMxNjE1NjQ1MTswMDsn\"",
    "id": "1490682b-4a56-ee11-a75f-aa65dbdad41e",
    "lastModifiedDateTime": "2023-09-18T17:38:26.093Z",
    "type": "General",
    "number": "TEST001",
    "tablelineno": 10000,
    "lineno": 10,
    "comment": "",
    "date": "0001-01-01",
    "tablesubtype": "1",
    "tablename": "Service Header"
}
```

This is tested against a local docker container running BC Version: W1 22.5 (Platform 22.0.60594.0 + Application 22.5.59966.60639)

**Comment by EmilDamsbo** [comment]
This repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by scruffy-sjb** [comment]
Thank you.

It was support who asked that I post the issue here……….

Simon

**Comment by EmilDamsbo** [comment]
@scruffy-sjb in that case, please inform them that they are mistaken and ask to re-open the support case. They might need to escalate the ticket from first line support. In this repository we only deal with the AL language, compiler, Visual Studio Code extension, and surrounding tooling. Troubleshooting the APIs for Business Central is typically dealt with via support tickets. Apologies for the confusing back-and-forth experience.

**Comment by scruffy-sjb** [comment]
Many thanks

Simon
